name: Run Tests on Pull Request

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up   
 Java environment
        uses: actions/setup-java@v3
        with:
          java-version: 11   

      - name: Build project
        run: ./gradlew build
      - name: Run tests with JUnit reporter
        run: ./gradlew test --tests '*Test'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test/TEST-*.xml
