name: Run JUnit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set   
 up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11   

      - name: Build and run tests
        run: ./gradlew build test
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: build/reports/junit/TEST-*.xml
